ALTER TABLE `cms_user_groups` ADD INDEX ( `alias` );
ALTER TABLE `cms_online` ADD INDEX ( `sess_id` , `ip` )
ALTER TABLE `cms_modules_bind` ADD INDEX ( `menu_id` );
ALTER TABLE `cms_modules_bind` ADD INDEX ( `module_id` );
ALTER TABLE `cms_modules` ADD INDEX ( `position` , `published` , `ordering` );
ALTER TABLE `cms_components` ADD INDEX ( `link` );
ALTER TABLE `cms_menu` ADD INDEX ( `parent_id` );
ALTER TABLE `cms_online` ADD INDEX ( `user_id` );
ALTER TABLE `cms_filters` ADD INDEX ( `published` );
ALTER TABLE `cms_comments` ADD INDEX ( `target` , `target_id` );
ALTER TABLE `cms_users` ADD INDEX ( `is_deleted` , `is_locked` , `regdate` );
ALTER TABLE `cms_event_hooks` ADD INDEX `event` ( `event` , `plugin_id` );
ALTER TABLE `cms_photo_albums` ADD INDEX `al1` ( `parent_id` , `NSDiffer` );
ALTER TABLE `cms_users` ADD INDEX ( `login` );
ALTER TABLE `cms_user_profiles` ADD INDEX ( `user_id` );
ALTER TABLE `cms_user_friends` ADD INDEX `frend` ( `to_id` , `from_id` );
ALTER TABLE `cms_user_awards` ADD INDEX `aw1` ( `user_id` , `pubdate` );
ALTER TABLE `cms_user_photos` ADD INDEX ( `user_id` );
ALTER TABLE `cms_user_wall` ADD INDEX `wall1` ( `user_id` , `usertype` );
ALTER TABLE `cms_user_msg` ADD INDEX `tid` ( `to_id` , `is_new` );
ALTER TABLE `cms_user_karma` ADD INDEX ( `user_id` );
ALTER TABLE `cms_user_files` ADD INDEX ( `user_id` );
ALTER TABLE `cms_user_clubs` ADD INDEX ( `user_id` );
ALTER TABLE `cms_user_clubs` ADD INDEX ( `club_id` );
ALTER TABLE `cms_board_items` ADD INDEX ( `published` , `pubdate` );
ALTER TABLE `cms_blog_posts` ADD INDEX ( `published` , `pubdate` );
ALTER TABLE `cms_content` ADD INDEX `lates` ( `published` , `showlatest`, `pubdate` );
ALTER TABLE `cms_tags` ADD INDEX ( `tag` );
ALTER TABLE `cms_content` ADD INDEX ( `category_id` , `published` , `pubdate` );
ALTER TABLE `cms_category` ADD INDEX ( `NSLeft` , `NSRight` );
ALTER TABLE `cms_category` ADD INDEX ( `parent_id` , `published` , `id` );